### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by mvexel** [osmlab/codes-of-conduct#11]
Not sure where else to put this, but I was reading [the new StackExchange CoC](http://meta.stackexchange.com/questions/240839/the-new-new-be-nice-policy-code-of-conduct-updated-with-your-feedback?cb=1) just now and wanted to share.

It has some shortcomings to my mind - notably taking the stated and intended vagueness / incompleteness too far - but I liked some other things:

* A paragraph specifically dedicated to being welcoming and patient to newcomers. We don't really address this specifically. Worth adding?
* This: _If you don't have time to say something politely, just leave it for someone who does._

**Comment by iandees** [comment]
I'm closing this as there's no actionable items right now.
